# yaml-language-server: $schema=https://golangci-lint.run/jsonschema/golangci.jsonschema.json

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports

linters-settings:
  goimports:
    local-prefixes: github.com/mkhoshkam/orderbook

issues:
  exclude-rules:
    - path: "_test\\.go"
      linters:
        - gosec
    - path: "_test\\.go"
      linters:
        - gomnd 